source 'https://github.com/CocoaPods/Specs.git'

target 'PXMaskButton', :exclusive => true do
  pod "PXMaskButton", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PXMaskButton", :path => "../"


end
